baseURL = "http://example.org/"
title = "Notes on Watchmen"
theme = "now-theme"
relativeURLs = false

[menu]
  [[menu.main]]
    name = "Chapters"
    identifier = "chapters"
    url = "/chapters/"
  [[menu.main]]
    name = "Pages"
    identifier = "pages"
    url = "/pages/"
