baseURL = "http://example.org/"
languageCode = "en-us"
title = "Notes on Watchmen"
theme="now-theme"
relativeURLs=true

[menu]
  [[menu.main]]
    name = "Chapters"
    identifier = "chapters"
    url = "/chapters/"
