baseURL = "http://example.org/"
title = "Notes on Watchmen"
theme = "now-theme"
relativeURLs = false

[menu]
  [[menu.main]]
    name = "Characters"
    identifier = "characters"
    url = "/characters/"
    weight = 10

  [[menu.main]]
    name = "Chapters"
    identifier = "chapters"
    url = "/chapters/"
    weight = 20

  [[menu.main]]
    name = "Pages"
    identifier = "pages"
    url = "/pages/"
    weight = 30
