baseURL = "http://example.org/"
title = "Notes on Watchmen"
theme = "now-theme"
relativeURLs = false

[menu]
  [[menu.main]]
    name = "Chapters"
    identifier = "chapters"
    url = "/chapters/"
    weight = 10

  [[menu.main]]
    name = "Pages"
    identifier = "pages"
    url = "/pages/"
    weight = 20
    
  [[menu.main]]
    name = "Characters"
    identifier = "characters"
    url = "/characters/"
    weight = 30


pygmentsUseClasses=true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
