baseURL = "http://example.org/"
languageCode = "en-us"
title = "Notes on Watchmen"
theme="mytheme"
relativeURLs=true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"

  [[menu.main]]
    identifier = "chapters"
    name = "chapters"
    url = "/chapters/"
